<?php

declare(strict_types=1);

return [

    /*
    |--------------------------------------------------------------------------
    | Renderer
    |--------------------------------------------------------------------------
    |
    | This is the single most consequential setting in the whole application for a
    | Bangla-medium school, and it deserves an explanation rather than a default.
    |
    |   browsershot - headless Chromium via spatie/browsershot. The ONLY option that
    |                 shapes Bengali correctly, because Chromium runs HarfBuzz. Bengali
    |                 is a complex script: "ক্ষ" is three codepoints that must be drawn
    |                 as one conjunct glyph, and "কি" puts the vowel BEFORE the
    |                 consonant it follows in memory. Requires Node and Chromium, so it
    |                 needs a VPS. Use this if you possibly can.
    |
    |   mpdf        - pure PHP, and the only pure-PHP renderer with a usable Indic
    |                 shaper (set useOTL). Imperfect on rare conjuncts but legible and
    |                 correct for ordinary Bangla names. This is the shared-cPanel
    |                 answer.
    |
    |   dompdf      - fast, ubiquitous, and CANNOT shape Bengali. It will render
    |                 "রফিকুল" as disconnected letters in the wrong order. Acceptable
    |                 ONLY for English-only output. It is not the default for that
    |                 reason.
    |
    */

    'driver' => env('PDF_DRIVER', 'mpdf'),

    'disk' => env('PDF_DISK', 'local'),

    'directory' => env('PDF_DIRECTORY', 'documents'),

    /*
    |--------------------------------------------------------------------------
    | Bengali font
    |--------------------------------------------------------------------------
    |
    | Nikosh is the Bangladesh government standard and is freely redistributable;
    | SolaimanLipi and Kalpurush are the common alternatives. Drop the .ttf into
    | storage/fonts/ and mPDF will pick it up. The family name below must match what
    | the Blade templates use in `font-family`.
    |
    */

    'fonts' => [
        'path' => storage_path('fonts'),
        'bengali_family' => env('PDF_BENGALI_FONT', 'nikosh'),
        'bengali_file' => env('PDF_BENGALI_FONT_FILE', 'Nikosh.ttf'),
        'fallback_family' => 'DejaVu Sans',
    ],

    /*
    |--------------------------------------------------------------------------
    | Browsershot binaries
    |--------------------------------------------------------------------------
    |
    | Left null so Browsershot uses whatever is on PATH. Shared hosting that has Node
    | in a non-standard location needs these set explicitly.
    |
    */

    'browsershot' => [
        'node_binary' => env('BROWSERSHOT_NODE_BINARY'),
        'npm_binary' => env('BROWSERSHOT_NPM_BINARY'),
        'chrome_path' => env('BROWSERSHOT_CHROME_PATH'),
        'timeout' => (int) env('BROWSERSHOT_TIMEOUT', 120),
        // --no-sandbox is required on most VPS images running as root. It lowers
        // Chromium's isolation, which is acceptable here only because the HTML we feed
        // it is generated by our own templates, never by a visitor.
        'no_sandbox' => (bool) env('BROWSERSHOT_NO_SANDBOX', true),
    ],

    /*
    |--------------------------------------------------------------------------
    | Batch behaviour
    |--------------------------------------------------------------------------
    |
    | chunk: how many documents one queued job renders. Chromium costs roughly 150ms
    | and 80MB per document, so 25 keeps a job under a typical 60s worker timeout while
    | still amortising the browser startup.
    |
    | merge: producing one print-ready PDF for the batch requires a merge tool. When
    | none is available the batch still succeeds - the operator downloads a zip instead
    | - so this must degrade rather than fail.
    |
    */

    'batch' => [
        'chunk' => (int) env('PDF_BATCH_CHUNK', 25),
        'queue' => env('PDF_QUEUE', 'documents'),
        'merge' => (bool) env('PDF_MERGE_BATCH', true),
    ],

    /*
    |--------------------------------------------------------------------------
    | QR / barcode
    |--------------------------------------------------------------------------
    */

    'qr' => [
        'size' => (int) env('QR_SIZE', 140),
        'margin' => 0,
        // Quartile correction. A card that lives in a school bag gets creased and
        // scuffed; L-level correction stops scanning after very little damage.
        'error_correction' => 'Q',
        'format' => env('QR_FORMAT', 'svg'),
    ],

    'barcode' => [
        'type' => env('BARCODE_TYPE', 'C128'),
        'height' => 40,
        'width_factor' => 2,
    ],
];
