<section class="w-full space-y-8">
    <div class="space-y-1">
        <flux:heading size="xl">{{ __('Welcome back, :name', ['name' => auth()->user()->name]) }}</flux:heading>
        <flux:text>{{ __('Here is the latest overview for your school workspace.') }}</flux:text>
    </div>

    @if (in_array($role, ['super_admin', 'admin'], true))
        <div class="grid grid-cols-1 gap-6 sm:grid-cols-2 xl:grid-cols-5">
            @foreach ([['Students', $metrics['students'] ?? 0], ['Teachers', $metrics['teachers'] ?? 0], ["Today's Attendance", ($metrics['attendance'] ?? 0).'%'], ["Today's Income", '৳'.number_format((float)($metrics['income'] ?? 0), 2)], ["Today's Expenses", '৳'.number_format((float)($metrics['expenses'] ?? 0), 2)]] as [$label, $value])
                <flux:card wire:key="admin-stat-{{ str($label)->slug() }}" class="space-y-2"><flux:text>{{ __($label) }}</flux:text><flux:heading size="xl">{{ $value }}</flux:heading></flux:card>
            @endforeach
        </div>
        <flux:card class="space-y-4"><flux:heading size="lg">{{ __('Recent Fee Collections') }}</flux:heading><flux:table><flux:table.columns><flux:table.column>{{ __('Student') }}</flux:table.column><flux:table.column>{{ __('Receipt') }}</flux:table.column><flux:table.column>{{ __('Time') }}</flux:table.column><flux:table.column align="end">{{ __('Amount') }}</flux:table.column></flux:table.columns><flux:table.rows>@forelse($recentPayments as $payment)<flux:table.row :key="$payment['receipt']"><flux:table.cell variant="strong">{{ $payment['student'] }}</flux:table.cell><flux:table.cell>{{ $payment['receipt'] }}</flux:table.cell><flux:table.cell>{{ $payment['paid_at'] }}</flux:table.cell><flux:table.cell align="end">৳{{ number_format($payment['amount'],2) }}</flux:table.cell></flux:table.row>@empty<flux:table.row><flux:table.cell colspan="4">{{ __('No recent fee collections.') }}</flux:table.cell></flux:table.row>@endforelse</flux:table.rows></flux:table></flux:card>
    @elseif ($role === 'teacher')
        <div class="grid grid-cols-1 gap-6 md:grid-cols-3"><flux:card><flux:text>{{ __('Students in Assigned Classes') }}</flux:text><flux:heading size="xl">{{ $metrics['students'] ?? 0 }}</flux:heading></flux:card><flux:card><flux:text>{{ __("Today's Attendance") }}</flux:text><flux:heading size="xl">{{ $metrics['attendance_status'] ?? __('Not recorded') }}</flux:heading></flux:card><flux:card><flux:text>{{ __('Pending Leave Requests') }}</flux:text><flux:heading size="xl">{{ $metrics['pending_leaves'] ?? 0 }}</flux:heading></flux:card></div>
        <flux:card class="space-y-4"><flux:heading size="lg">{{ __("Today's Classes") }}</flux:heading><div class="divide-y divide-zinc-200 dark:divide-zinc-700">@forelse($todayRoutines as $routine)<div class="flex items-center justify-between gap-4 py-3"><div><div class="font-medium">{{ $routine['subject'] }} — {{ __('Section :section', ['section' => $routine['section']]) }}</div><flux:text>{{ $routine['period'] }}</flux:text></div><flux:badge color="blue">{{ $routine['time'] }}</flux:badge></div>@empty<flux:text>{{ __('No classes are scheduled for today.') }}</flux:text>@endforelse</div></flux:card>
    @elseif (in_array($role, ['student', 'guardian'], true))
        <div class="grid grid-cols-1 gap-6 md:grid-cols-3"><flux:card><flux:text>{{ __('Attendance') }}</flux:text><flux:heading size="xl">{{ $metrics['attendance'] ?? 0 }}%</flux:heading></flux:card><flux:card><flux:text>{{ __('Outstanding Fees') }}</flux:text><flux:heading size="xl">৳{{ number_format((float)($metrics['fee_due'] ?? 0),2) }}</flux:heading></flux:card><flux:card><flux:text>{{ __('Latest Exam Result') }}</flux:text><flux:heading size="xl">{{ $metrics['gpa'] ?? '—' }} <span class="text-base">({{ $metrics['grade'] ?? '—' }})</span></flux:heading></flux:card></div>
        @if (($metrics['fee_due'] ?? 0) > 0)<flux:card class="border-amber-300 bg-amber-50 dark:border-amber-700 dark:bg-amber-950"><flux:heading>{{ __('Fee payment pending') }}</flux:heading><flux:text>{{ __('Please clear the outstanding balance to keep the student account up to date.') }}</flux:text></flux:card>@endif
    @endif

    <div class="space-y-4"><div><flux:heading size="lg">{{ __('Notice Board') }}</flux:heading><flux:text>{{ __('Latest announcements for the school community.') }}</flux:text></div><div class="grid grid-cols-1 gap-6 md:grid-cols-3">@forelse($notices as $notice)<flux:card wire:key="notice-{{ str($notice['title'])->slug() }}" class="space-y-3"><div class="flex items-start justify-between gap-3"><flux:heading>{{ $notice['title'] }}</flux:heading><flux:badge color="zinc">{{ $notice['date'] }}</flux:badge></div><flux:text>{{ $notice['content'] }}</flux:text></flux:card>@empty<flux:card class="md:col-span-3"><flux:text>{{ __('No active notices are available.') }}</flux:text></flux:card>@endforelse</div></div>
</section>
